name: InstallAngular
description: this document installs node on ubuntu
schemaVersion: 1.0

phases:
    - name: build
      steps:
        - name: InstallAngular
          action: ExecuteBash
          inputs:
            commands:
                - sudo amazon-linux-extras install -y docker
                - sudo service docker start
                - sudo usermod -a -G docker ec2-user
                - sudo chkconfig docker on
                - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                - sudo chmod +x /usr/local/bin/docker-compose